[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/js/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/data/*.m3u"
  [headers.values]
    Content-Type = "application/vnd.apple.mpegurl"
    Cache-Control = "no-cache, no-store, must-revalidate"

[[redirects]]
  from = "/serviceWorker.js"
  to = "/serviceWorker.js"
  status = 200
  headers = {Cache-Control = "no-cache"}

# Redirigir todo a index.html para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200